### ISSUE TITLE
Реализация изменения данных через виджет календаря

### ISSUE THREAD

**Issue by haritonasty** [Integraali10/Calendarlo#10]

**Comment by Integraali10** [comment]
- [ ] Требуется реализовать возможность менять данные в главном окне и в виджете календаря прямым выбором дат (по щелчку мыши, например)

**Comment by IgnatievAnton** [comment]
протестировано, в некоторых случаях некорректная обработка

**Comment by Integraali10** [comment]
Чеки решены в версии 69

**Comment by IgnatievAnton** [comment]
протестировано
