### ISSUE TITLE
Запушить первую версию приложения

### ISSUE THREAD

**Issue by Integraali10** [Integraali10/Calendarlo#14]

**Comment by Integraali10** [comment]
- [ ] Приложение падает при нажатии на крестик

- [ ]  Все так же требуется либа с красивым и сложным именем libgcc_s_dw2-1.dll

**Comment by Integraali10** [comment]
- [ ] При инсталляции почему-то деактивируется кнопка "Печать"

**Comment by IgnatievAnton** [comment]
Протестировано
