### ISSUE TITLE
Рефакторинг кода

### ISSUE THREAD

**Issue by Integraali10** [Integraali10/Calendarlo#18]
- [x] исправить излишнее копирование кода
- [x] найти и вырезать нелогичные вещи (уровня year/=2 && year /=4)
- [x] удалить hard-written данные - или хотя бы нивелировать
- [x] исправить орфографию в названиях сущностей (ДРАТУТИ, ДРОУ_РЩД)
- [x] решить проблему с выводом версии
upd. задача решена в версии 11

**Comment by DariaSakhno** [comment]
Done!
