### ISSUE TITLE
Ввод данных сотрудника

### ISSUE THREAD

**Issue by haritonasty** [Integraali10/Calendarlo#5]

**Comment by DariaSakhno** [comment]
необходима тестировка
версия 1.12

**Comment by IgnatievAnton** [comment]
протестировано

**Comment by Integraali10** [comment]
- [ ] Проследить за кодировками при записи в файл и из файла

**Comment by Integraali10** [comment]
- [ ] По хорошему, необходим регексп на ФИО, чтобы в имени ничего не было, кроме букв, апострофов и пробелов. Задачу надо обсудить с экспертом

**Comment by IgnatievAnton** [comment]
Протестировано
