### ISSUE TITLE
Обработка дат и смен

### ISSUE THREAD

**Issue by haritonasty** [Integraali10/Calendarlo#6]

**Comment by DariaSakhno** [comment]
необходима тестировка
версия 1.12

**Comment by IgnatievAnton** [comment]
протестировано, в некоторых случаях некорректная обработка

**Comment by Integraali10** [comment]
- [ ] Отображение смен зависит от фазы луны, в какой момент оно чинится не ясно

**Comment by IgnatievAnton** [comment]
протестировано, в некоторых случаях некорректная обработка

**Comment by Integraali10** [comment]
Чеки решены в версии 69

**Comment by Integraali10** [comment]
- [ ] Есть проблема с кьюдэйтбокс - невозможно выбрать количество дней меньшее для одного месяца - почистить логику в changeToVocation ()

**Comment by IgnatievAnton** [comment]
протестировано
