### ISSUE TITLE
Реализация печати

### ISSUE THREAD

**Issue by haritonasty** [Integraali10/Calendarlo#9]

**Comment by Integraali10** [comment]
- [ ]  Размеры календаря больше стандартного размера листа А4 . **Suggestion:** поискать возможность автоматического ресайза

- [ ] Если не нажать кнопку "Показать" , в печать занесется серый фон. **Suggestion:** вынести предупреждение, либо инициализировать данные только с вводом данных сотрудника

- [ ] Приходится следить за тем, чтобы в свойствах печати ориентация соответствовало выбранному в приложении.

**Comment by IgnatievAnton** [comment]
Протестировано
